/************************************************************\
**	Copyright (c) 2012-2024 Anlogic Inc.
**	All Right Reserved.
\************************************************************/
/************************************************************\
**	Build time: Oct 31 2024 09:07:24
**	TD version	:	5.9.122301
************************************************************/
`timescale 1ps/1ps
module system_AXI_Width_Converter_0
(
  input                         aclk,
  input                         aresetn,
  input   [7:0]                 us_awid,
  input   [31:0]                us_awaddr,
  input   [7:0]                 us_awlen,
  input   [2:0]                 us_awsize,
  input   [1:0]                 us_awburst,
  input   [0:0]                 us_awlock,
  input   [3:0]                 us_awcache,
  input   [2:0]                 us_awprot,
  input   [3:0]                 us_awregion,
  input   [3:0]                 us_awqos,
  input                         us_awvalid,
  output                        us_awready,
  input   [127:0]               us_wdata,
  input   [15:0]                us_wstrb,
  input                         us_wlast,
  input                         us_wvalid,
  output                        us_wready,
  output  [7:0]                 us_bid,
  output  [1:0]                 us_bresp,
  output                        us_bvalid,
  input                         us_bready,
  input   [7:0]                 us_arid,
  input   [31:0]                us_araddr,
  input   [7:0]                 us_arlen,
  input   [2:0]                 us_arsize,
  input   [1:0]                 us_arburst,
  input   [0:0]                 us_arlock,
  input   [3:0]                 us_arcache,
  input   [2:0]                 us_arprot,
  input   [3:0]                 us_arregion,
  input   [3:0]                 us_arqos,
  input                         us_arvalid,
  output                        us_arready,
  output  [7:0]                 us_rid,
  output  [127:0]               us_rdata,
  output  [1:0]                 us_rresp,
  output                        us_rlast,
  output                        us_rvalid,
  input                         us_rready,
  output  [31:0]                ds_awaddr,
  output  [7:0]                 ds_awlen,
  output  [2:0]                 ds_awsize,
  output  [1:0]                 ds_awburst,
  output  [0:0]                 ds_awlock,
  output  [3:0]                 ds_awcache,
  output  [2:0]                 ds_awprot,
  output  [3:0]                 ds_awregion,
  output  [3:0]                 ds_awqos,
  output                        ds_awvalid,
  input                         ds_awready,
  output  [63:0]                ds_wdata,
  output  [7:0]                 ds_wstrb,
  output                        ds_wlast,
  output                        ds_wvalid,
  input                         ds_wready,
  input   [1:0]                 ds_bresp,
  input                         ds_bvalid,
  output                        ds_bready,
  output  [31:0]                ds_araddr,
  output  [7:0]                 ds_arlen,
  output  [2:0]                 ds_arsize,
  output  [1:0]                 ds_arburst,
  output  [0:0]                 ds_arlock,
  output  [3:0]                 ds_arcache,
  output  [2:0]                 ds_arprot,
  output  [3:0]                 ds_arregion,
  output  [3:0]                 ds_arqos,
  output                        ds_arvalid,
  input                         ds_arready,
  input   [63:0]                ds_rdata,
  input   [1:0]                 ds_rresp,
  input                         ds_rlast,
  input                         ds_rvalid,
  output                        ds_rready
);

  axi_width_converter_top_86cf6e4e58e3
  #(
      .AL_AXI_PROTOCOL(0),
      .AL_US_AXI_ID_WIDTH(8),
      .AL_AXI_ADDR_WIDTH(32),
      .AL_US_AXI_DATA_WIDTH(128),
      .AL_DS_AXI_DATA_WIDTH(64),
      .AL_AXI_SUPPORTS_WRITE(1),
      .AL_AXI_SUPPORTS_READ(1),
      .AL_MAX_SPLIT_BEATS(16),
      .AL_PACKING_LEVEL(2)
  )axi_width_converter_top_86cf6e4e58e3_Inst
  (
      .aclk(aclk),
      .aresetn(aresetn),
      .us_awid(us_awid),
      .us_awaddr(us_awaddr),
      .us_awlen(us_awlen),
      .us_awsize(us_awsize),
      .us_awburst(us_awburst),
      .us_awlock(us_awlock),
      .us_awcache(us_awcache),
      .us_awprot(us_awprot),
      .us_awregion(us_awregion),
      .us_awqos(us_awqos),
      .us_awvalid(us_awvalid),
      .us_awready(us_awready),
      .us_wdata(us_wdata),
      .us_wstrb(us_wstrb),
      .us_wlast(us_wlast),
      .us_wvalid(us_wvalid),
      .us_wready(us_wready),
      .us_bid(us_bid),
      .us_bresp(us_bresp),
      .us_bvalid(us_bvalid),
      .us_bready(us_bready),
      .us_arid(us_arid),
      .us_araddr(us_araddr),
      .us_arlen(us_arlen),
      .us_arsize(us_arsize),
      .us_arburst(us_arburst),
      .us_arlock(us_arlock),
      .us_arcache(us_arcache),
      .us_arprot(us_arprot),
      .us_arregion(us_arregion),
      .us_arqos(us_arqos),
      .us_arvalid(us_arvalid),
      .us_arready(us_arready),
      .us_rid(us_rid),
      .us_rdata(us_rdata),
      .us_rresp(us_rresp),
      .us_rlast(us_rlast),
      .us_rvalid(us_rvalid),
      .us_rready(us_rready),
      .ds_awaddr(ds_awaddr),
      .ds_awlen(ds_awlen),
      .ds_awsize(ds_awsize),
      .ds_awburst(ds_awburst),
      .ds_awlock(ds_awlock),
      .ds_awcache(ds_awcache),
      .ds_awprot(ds_awprot),
      .ds_awregion(ds_awregion),
      .ds_awqos(ds_awqos),
      .ds_awvalid(ds_awvalid),
      .ds_awready(ds_awready),
      .ds_wdata(ds_wdata),
      .ds_wstrb(ds_wstrb),
      .ds_wlast(ds_wlast),
      .ds_wvalid(ds_wvalid),
      .ds_wready(ds_wready),
      .ds_bresp(ds_bresp),
      .ds_bvalid(ds_bvalid),
      .ds_bready(ds_bready),
      .ds_araddr(ds_araddr),
      .ds_arlen(ds_arlen),
      .ds_arsize(ds_arsize),
      .ds_arburst(ds_arburst),
      .ds_arlock(ds_arlock),
      .ds_arcache(ds_arcache),
      .ds_arprot(ds_arprot),
      .ds_arregion(ds_arregion),
      .ds_arqos(ds_arqos),
      .ds_arvalid(ds_arvalid),
      .ds_arready(ds_arready),
      .ds_rdata(ds_rdata),
      .ds_rresp(ds_rresp),
      .ds_rlast(ds_rlast),
      .ds_rvalid(ds_rvalid),
      .ds_rready(ds_rready)
  );
endmodule
