set_ip_property GBE0_TXCLK_FREQ  125 [get_cells {ARM_Processor_System_59fb6a0bf2ca_Inst/DR1_PHY_PROCESSOR_SYSTEM_Inst}]
set_ip_property GBE0_TXCLK_PHA 0 [get_cells {ARM_Processor_System_59fb6a0bf2ca_Inst/DR1_PHY_PROCESSOR_SYSTEM_Inst}]
set_ip_property IOPLL_400M_FREQ 400 [get_cells {ARM_Processor_System_59fb6a0bf2ca_Inst/DR1_PHY_PROCESSOR_SYSTEM_Inst}] 
set_ip_property P2F_CLK0_DIV 2 [get_cells {ARM_Processor_System_59fb6a0bf2ca_Inst/DR1_PHY_PROCESSOR_SYSTEM_Inst}]
