/* IDE_PATH       : E:/FPGA/Anlu/bin/td.exe */
/* IDE_VERSION    : Release: 6.2.1 Build: 168116  */
/* HPF_EXPORT_TIME: 2026/10/07 13:47:01 */
/* HPFTool_Version: 2025/07/09 15:19:18 */

#ifndef __SOC_PLAT_H
#define __SOC_PLAT_H

#ifdef __cplusplus
extern "C" {
#endif

#define             IDE_VERSION ("Release: 6.2.1 Build: 168116 ")
#define         HPF_EXPORT_TIME ("2026/10/07 13:47:01")
#define BITSTREAM_GENERATE_TIME ("2026/10/ 7 13:44:00")
#define         HPFTool_Version ("2025/07/09 15:19:18")
#define    Bank200_IO_Voltage  ("LVCMOS 3.3V")
#define    Bank201_IO_Voltage  ("LVCMOS 1.8V")

#define SYSCTRL_NS_BOOT_MODE      ((0XF8800000UL) + (0X00000200UL))
#define ALFSBL_BOOTMODE_JTAG      (0x0U)
#define ALFSBL_BOOTMODE_QSPI24    (0x1U)
#define ALFSBL_BOOTMODE_EMMC      (0x2U)
#define ALFSBL_BOOTMODE_QSPI32    (0x3U)
#define ALFSBL_BOOTMODE_NAND      (0x4U)
#define ALFSBL_BOOTMODE_SD        (0x5U)
#define ALFSBL_BOOTMODE_EMMC_RAW  (0x6U)
#define ALFSBL_BOOTMODE_EMMC1     (0x7U)


#define HPF_VERSION   202507
#define USE_DDR_DEBUG

#ifndef _UL
#define _UL unsigned int
#endif

#define __HPF_AARCH64        0
#define __HPF_RISCV          1
#define __ARCH   __HPF_AARCH64

/* config opcode */
#define CONFIG_EXIT         0U
#define CONFIG_CLEAR        1U
#define CONFIG_WRITE_REG    2U
#define CONFIG_MASKWRITE    3U
#define CONFIG_MASKPOLL     4U
#define CONFIG_MASKDELAY    5U
#define PLAT_ERR_CODE       6U

#define CONFIG_POLL_TIME    100000

/* Encode number of arguments */
#define CONFIG_REG_EXIT()                    ( (CONFIG_EXIT      << 4 ) | 0 )
#define CONFIG_REG_CLEAR(addr)               ( (CONFIG_CLEAR     << 4 ) | 1 ) , addr
#define CONFIG_WRITE(addr,val)               ( (CONFIG_WRITE_REG << 4 ) | 2 ) , addr, val
#define CONFIG_REG_MASK(addr,mask,val)       ( (CONFIG_MASKWRITE << 4 ) | 3 ) , addr, mask, val
#define CONFIG_REG_MASKPOLL(addr,mask,val)   ( (CONFIG_MASKPOLL  << 4 ) | 3 ) , addr, mask, val

/* Returns codes  of PLAT_Init */
#define PLAT_INIT_SUCCESS         (0)    // success
#define PLAT_INIT_OPCODE_ERROR    (1)    // config opcode error
#define PLAT_INIT_VERSION_ERROR   (2)    // data error
#define PLAT_INIT_TIMEOUT         (3)    // timeout

/* Silicon Versions */
#define SOC_VERSION_1 0


/* This flag used by FSBL to check whether apu_post_config() proc exists */
#define PLAT_POST_CONFIG

/* Clock frequency of all peripherals, generated by system automatically. */
#define Hz                                        1
#define MHz                                 1000000
#define MHZ                                 1000000
#define I2C_CLOCK                         100000000
#define CAN_CLOCK                          80000000
#define GBE_CLOCK                         500000000
#define ADC_CLOCK                          50000000
#define GPIO_CLOCK                         12500000
#define CPU_CLOCK                         999900000
#define GBE0_PTP_CLOCK                    100000000
#define IO_1000_FREQ                      999900000
#define IO_25_FREQ                         24997500
#define IO_400_FREQ                       399960000
#define IO_80_FREQ                         79992000
#define SYSTEM_CLOCK                       33333333
#define P2F_CLOCK_0                       199980000
#define QSPI_2ND_DIVISOR                          2
#define QSPI_CLOCK                         19998000
#define MMC_CLOCK                         399960000
#define MMC0_IO_FREQ                       49995000
#define MMC1_IO_FREQ                       49995000
#define UART_CLOCK                         49995000


/* default value to freq start */
#define SPI_CLOCK                           200000000
#define SPI_IP_CLOCK                        SPI_CLOCK
#define TC_CLOCK                            200000000
#define WDT_CLOCK                            16665000
#define GBE1_PTP_CLOCK                      100000000
#define GBE_PTP_CLOCK                       100000000
#define QSPI_IO_FREQ             (QSPI_CLOCK/QSPI_2ND_DIVISOR)
/* default value to freq end*/


/* PLL configuration, generated by hpfTool automatically. */
#define CPU_gm_cell                               1
#define CPU_icp                                  10
#define CPU_kvco                                  0
#define CPU_lpf_cap                               2
#define CPU_lpf_res                               4
#define IO_gm_cell                                1
#define IO_icp                                   10
#define IO_kvco                                   0
#define IO_lpf_cap                                2
#define IO_lpf_res                                4
#define CPU_CLOCK_RATIO                         421
#define CPU_FBK_DIV                             120
#define CPU_OUT_DIV                               2
#define CPU_REF_DIV                               2
#define IO1000_OUT_DIV                            2
#define IO25_OUT_DIV                             80
#define IO400_OUT_DIV                             5
#define IO80_OUT_DIV                             25
#define IO_FBK_DIV                              120
#define IO_REF_DIV                                2


/* device config, generated by hpfTool automatically. and
* drivers which enabled by user, generated by hpfTool automatically.
*/
#define CANFD                                     0
#define CAN20B                                    1
#define MPUPS_ENABLE
#define DMAPS_ENABLE
#define ADCPS_ENABLE
#define GBE_RGMII	        0
#define GBE_GMII	        1
#define GBE_RMII	        2
#define GBE_MII		        3
// #define CAN0PS_ENABLE
// #define CAN1PS_ENABLE
#define DDR_AVAILABLE
#define DDRC_ADDR_MAP                  ROW_COL_BANK
#define DDRC_COMP_DENSITY                      4096
#define DDRC_SPEED_BIN        _SPEED_BIN_DDR3_1333G
#define DDRC_COMP_TYPE           DDR_COMP_WIDTH_x16
#define FD_PARA_DRAM_DRV                         40
#define FD_PARA_DRAM_ODT                         40
#define DDRC_ECC_EN                        ECC_NONE
#define FD_PARA_HOST_DRV_AC                      40
#define FD_PARA_HOST_DRV_DX                      40
#define FD_PARA_HOST_ODT_DX                      40
#define DDRC_IO_VOL                            1.35
#define DDRC_PZQ_CONF                             0
#define DDRC_RDBI                                 0
#define DDRC_DDR_SPEED                         1333
#define DDRC_TRAINING_EN                          1
#define DDRC_DELAY_B0_AC                          0
#define DDRC_DELAY_B0_DQ                          0
#define DDRC_DDR_TYPE                          DDR3
#define DDRC_VREF                          Internal
#define DDRC_WDM_WDBI                          NONE
#define DDRC_DQ_WIDTH                            32
#define DDRPS_ENABLE                              1
#define GBE0PS_ENABLE
#define PSGBE0_INTERFACE_TYPE             GBE_RGMII
// #define GBE1PS_ENABLE
#define GPIOPL_ENABLE
#define GPIOPS_ENABLE
// #define I2C0PS_ENABLE
// #define I2C1PS_ENABLE
// #define __MMC0PS_BUS_WIDTH
// #define SMCPS_ENABLE
#define OSC_CLK                               33.33
#define QSPIPS_ENABLE
#define MMC0PS_ENABLE
#define MMC1PS_ENABLE
// #define SPI0PS_ENABLE
// #define SPI1PS_ENABLE
// #define TC0PS_ENABLE
// #define TC1PS_ENABLE
// #define UART0PS_ENABLE
#define UART1_BAUDRATE                       115200
#define UART1PS_ENABLE
#define USB0PS_ENABLE
// #define USB1PS_ENABLE
// #define WDTPS_ENABLE


/* default value to subip start */
#define PSGBE1_INTERFACE_TYPE               GBE_RGMII
#define MMC0PS_BUS_WIDTH                            4
/* default value to subip end*/


/* default value to DDr Controller params start */
// (1) ddr type, default: DDR3
#define DDR3                                        3
#define DDR4                                        4
#define FD_PARA_DDR_TYPE                DDRC_DDR_TYPE
// (2) ddr speed: default: 800
#define FD_PARA_DDR_SPEED              DDRC_DDR_SPEED
// (3) ddr dc width: 8, 16, 32,default: 32
#define FD_PARA_DQ_WIDTH                DDRC_DQ_WIDTH
// (4) ddrc io vol: 1.2, 1.35, 1.5,default: 1.5
#define FD_PARA_IO_VOLT                   DDRC_IO_VOL
// (5) ddrc vref, default: 0
#define External                                    1
#define Internal                                    0
#define FD_PARA_VREF                        DDRC_VREF
// (6) ddr pzq config, default: 0
#define FD_PARA_PZQ_ENABLE              DDRC_PZQ_CONF
// (7) ddr dram width: 8:x8, 16:x16,default: 8
#define DDR_COMP_WIDTH_x16                         16
#define DDR_COMP_WIDTH_x8                           8
#define FD_PARA_DRAM_WIDTH             DDRC_COMP_TYPE
// (8) ddr dram density:  512, 1024, 2048, 4096,8192, default: 4096
#define FD_PARA_DRAM_DENSITY        DDRC_COMP_DENSITY
// (9) ddr speed bin
#define _SPEED_BIN_DDR3_1066E                       2
#define _SPEED_BIN_DDR3_1066F                       3
#define _SPEED_BIN_DDR3_1066G                       4
#define _SPEED_BIN_DDR3_1333F                       5
#define _SPEED_BIN_DDR3_1333G                       6
#define _SPEED_BIN_DDR3_1333H                       7
#define _SPEED_BIN_DDR3_1333J                       8
#define _SPEED_BIN_DDR3_800D                        0
#define _SPEED_BIN_DDR3_800E                        1
#define _SPEED_BIN_DDR4_1600J                       9
#define _SPEED_BIN_DDR4_1600K                      10
#define _SPEED_BIN_DDR4_1600L                      11
#define FD_PARA_SPEED_BIN              DDRC_SPEED_BIN
// (10) ddr wdm sdbi, default: 0
#define NONE                                        0
#define WDM                                         1
#define FD_PARA_WDM                     DDRC_WDM_WDBI
// (11) ddr rdbi,default:0
#define RDBI                                        1
#define FD_PARA_RDBI                        DDRC_RDBI
// (12) ddr ecc: 0:None, 1:SideBand, 2:Inline.
#define ECC_0                                       0
#define ECC_Inline                                  2
#define ECC_NONE                                    0
#define ECC_SideBand                                1
#define FD_PARA_ECC                       DDRC_ECC_EN
// (13) ddr addr map
#define BANK_ROW_COL                                2
#define ROW_BANK_COL                                1
#define ROW_COL_BANK                                0
#define FD_PARA_ADDRMAP                 DDRC_ADDR_MAP
// (14) ddr training, default:0
#define FD_PARA_TRAINING             DDRC_TRAINING_EN
// (15.1) ddr train, byte0
#define FD_PARA_BYTE0_AC_DLY         DDRC_DELAY_B0_AC
// (15.1) ddr train, byte0
#define FD_PARA_BYTE0_DQS_DLY        DDRC_DELAY_B0_DQ
// (15.2) ddr train, byte1
#define FD_PARA_BYTE1_AC_DLY                      0.0
// (15.2) ddr train, byte1
#define FD_PARA_BYTE1_DQS_DLY                     0.0
// (15.3) ddr train, byte2
#define FD_PARA_BYTE2_AC_DLY                      0.0
// (15.3) ddr train, byte2
#define FD_PARA_BYTE2_DQS_DLY                     0.0
// (15.4) ddr train, byte3
#define FD_PARA_BYTE3_AC_DLY                      0.0
// (15.4) ddr train, byte3
#define FD_PARA_BYTE3_DQS_DLY                     0.0
/* default value to DDr Controller params end*/



#if defined(GBE0PS_ENABLE) && defined(GBE1PS_ENABLE)
#define GBE_DEVICE_ID -1
#endif

#if !defined(GBE0PS_ENABLE) && !defined(GBE1PS_ENABLE)
#define GBE_DEVICE_ID -1
#endif

#ifdef GBE0PS_ENABLE
#define GBE_DEVICE_ID 0
#endif

#ifdef GBE1PS_ENABLE
#define GBE_DEVICE_ID 1
#endif


/* ip driver filter */



/* this generated by FD automatically.*/
/*{{device}}*/
#define HAVE_ADCPS_DRIVER
// #define HAVE_CANPS_DRIVER
#define HAVE_DMAPS_DRIVER
#define HAVE_GBEPS_DRIVER
#define HAVE_GPIOPS_DRIVER
#define HAVE_IICPS_DRIVER
#define HAVE_IPCPS_DRIVER
#define HAVE_MMCPS_DRIVER
#define HAVE_MPUPS_DRIVER
#define HAVE_QSPIPS_DRIVER
#define HAVE_SMCPS_DRIVER
#define HAVE_SPIPS_DRIVER
#define HAVE_TCPS_DRIVER
#define HAVE_UARTPS_DRIVER
#define HAVE_USBPS_DRIVER
#define HAVE_WDTPS_DRIVER


/**
* @desc  : initialize soc platform according to user configuration
* @return {int} status code of platform initialization
*/
int  Soc_PlatInit();

/**
* @desc  : initialize ps_pl only according to user configuration
* @return {int} status code of pl_ps initialization
*/
int  Soc_PsPlInit();

int  Soc_PlatGetDeviceVersion();

/* debug info */



/* PL AXI IP instance start, generated by HPF automatically */
#define AL_AXI_DMA_NUM_INSTANCE                0
#define AL_AXI_ETH_LITE_NUM_INSTANCE           0
#define AL_AXI_GPIO_NUM_INSTANCE               0
#define AL_AXI_IIC_NUM_INSTANCE                0
#define AL_AXI_QSPI_NUM_INSTANCE               0
#define AL_AXI_SOFT_NPU_NUM_INSTANCE           0
#define AL_AXI_UART_LITE_NUM_INSTANCE          0
#define AL_AXI_VDMA_NUM_INSTANCE               0
/* PL AXI IP instance end, generated by HPF automatically */

#ifdef __cplusplus
}
#endif
#endif /* __SOC_PLAT_H */
