#########################################################################
# Copyright (c) 2023, Anlogic Inc. and Contributors. All rights reserved.

# SPDX-License-Identifier: BSD-3-Clause
#########################################################################


#########################################################################
# chip sources dir
#########################################################################

SRC_DIR += $(CHIP_DIR)/../common/src \
           $(CHIP_DIR)/src

INC_DIR += $(CHIP_DIR)/inc

# vim: syntax=make
