module system_uiFDMA_0 
#(
    parameter M_AXI_ADDR_WIDTH = 32 ,
    parameter M_AXI_DATA_WIDTH = 64 ,
    parameter M_AXI_ID = 10 ,
    parameter M_AXI_ID_WIDTH = 12 ,
    parameter M_AXI_MAX_BURST_LEN = 16
)
(
    input  [(M_AXI_ADDR_WIDTH - 1):0] I_fdma_waddr ,
    input             I_fdma_wareq ,
    input      [15:0] I_fdma_wsize ,
    output            O_fdma_wbusy ,
    input  [(M_AXI_DATA_WIDTH - 1):0] I_fdma_wdata ,
    output            O_fdma_wvalid ,
    input             I_fdma_wready ,
    input  [(M_AXI_ADDR_WIDTH - 1):0] I_fdma_raddr ,
    input             I_fdma_rareq ,
    input      [15:0] I_fdma_rsize ,
    output            O_fdma_rbusy ,
    output [(M_AXI_DATA_WIDTH - 1):0] O_fdma_rdata ,
    output            O_fdma_rvalid ,
    input             I_fdma_rready ,
    input             M_AXI_ACLK ,
    input             M_AXI_ARESETN ,
    output [(M_AXI_ID_WIDTH - 1):0] M_AXI_AWID ,
    output [(M_AXI_ADDR_WIDTH - 1):0] M_AXI_AWADDR ,
    output      [7:0] M_AXI_AWLEN ,
    output      [2:0] M_AXI_AWSIZE ,
    output      [1:0] M_AXI_AWBURST ,
    output            M_AXI_AWLOCK ,
    output      [3:0] M_AXI_AWCACHE ,
    output      [2:0] M_AXI_AWPROT ,
    output      [3:0] M_AXI_AWQOS ,
    output            M_AXI_AWVALID ,
    input             M_AXI_AWREADY ,
    output [(M_AXI_ID_WIDTH - 1):0] M_AXI_WID ,
    output [(M_AXI_DATA_WIDTH - 1):0] M_AXI_WDATA ,
    output [((M_AXI_DATA_WIDTH / 8) - 1):0] M_AXI_WSTRB ,
    output            M_AXI_WLAST ,
    output            M_AXI_WVALID ,
    input             M_AXI_WREADY ,
    input  [(M_AXI_ID_WIDTH - 1):0] M_AXI_BID ,
    input       [1:0] M_AXI_BRESP ,
    input             M_AXI_BVALID ,
    output            M_AXI_BREADY ,
    output [(M_AXI_ID_WIDTH - 1):0] M_AXI_ARID ,
    output [(M_AXI_ADDR_WIDTH - 1):0] M_AXI_ARADDR ,
    output      [7:0] M_AXI_ARLEN ,
    output      [2:0] M_AXI_ARSIZE ,
    output      [1:0] M_AXI_ARBURST ,
    output            M_AXI_ARLOCK ,
    output      [3:0] M_AXI_ARCACHE ,
    output      [2:0] M_AXI_ARPROT ,
    output      [3:0] M_AXI_ARQOS ,
    output            M_AXI_ARVALID ,
    input             M_AXI_ARREADY ,
    input  [(M_AXI_ID_WIDTH - 1):0] M_AXI_RID ,
    input  [(M_AXI_DATA_WIDTH - 1):0] M_AXI_RDATA ,
    input       [1:0] M_AXI_RRESP ,
    input             M_AXI_RLAST ,
    input             M_AXI_RVALID ,
    output            M_AXI_RREADY
) ;

    uiFDMA #(
        .M_AXI_ADDR_WIDTH(M_AXI_ADDR_WIDTH) ,
        .M_AXI_DATA_WIDTH(M_AXI_DATA_WIDTH) ,
        .M_AXI_ID(M_AXI_ID) ,
        .M_AXI_ID_WIDTH(M_AXI_ID_WIDTH) ,
        .M_AXI_MAX_BURST_LEN(M_AXI_MAX_BURST_LEN)
    ) uiFDMA (
        .I_fdma_waddr(I_fdma_waddr) ,
        .I_fdma_wareq(I_fdma_wareq) ,
        .I_fdma_wsize(I_fdma_wsize) ,
        .O_fdma_wbusy(O_fdma_wbusy) ,
        .I_fdma_wdata(I_fdma_wdata) ,
        .O_fdma_wvalid(O_fdma_wvalid) ,
        .I_fdma_wready(I_fdma_wready) ,
        .I_fdma_raddr(I_fdma_raddr) ,
        .I_fdma_rareq(I_fdma_rareq) ,
        .I_fdma_rsize(I_fdma_rsize) ,
        .O_fdma_rbusy(O_fdma_rbusy) ,
        .O_fdma_rdata(O_fdma_rdata) ,
        .O_fdma_rvalid(O_fdma_rvalid) ,
        .I_fdma_rready(I_fdma_rready) ,
        .M_AXI_ACLK(M_AXI_ACLK) ,
        .M_AXI_ARESETN(M_AXI_ARESETN) ,
        .M_AXI_AWID(M_AXI_AWID) ,
        .M_AXI_AWADDR(M_AXI_AWADDR) ,
        .M_AXI_AWLEN(M_AXI_AWLEN) ,
        .M_AXI_AWSIZE(M_AXI_AWSIZE) ,
        .M_AXI_AWBURST(M_AXI_AWBURST) ,
        .M_AXI_AWLOCK(M_AXI_AWLOCK) ,
        .M_AXI_AWCACHE(M_AXI_AWCACHE) ,
        .M_AXI_AWPROT(M_AXI_AWPROT) ,
        .M_AXI_AWQOS(M_AXI_AWQOS) ,
        .M_AXI_AWVALID(M_AXI_AWVALID) ,
        .M_AXI_AWREADY(M_AXI_AWREADY) ,
        .M_AXI_WID(M_AXI_WID) ,
        .M_AXI_WDATA(M_AXI_WDATA) ,
        .M_AXI_WSTRB(M_AXI_WSTRB) ,
        .M_AXI_WLAST(M_AXI_WLAST) ,
        .M_AXI_WVALID(M_AXI_WVALID) ,
        .M_AXI_WREADY(M_AXI_WREADY) ,
        .M_AXI_BID(M_AXI_BID) ,
        .M_AXI_BRESP(M_AXI_BRESP) ,
        .M_AXI_BVALID(M_AXI_BVALID) ,
        .M_AXI_BREADY(M_AXI_BREADY) ,
        .M_AXI_ARID(M_AXI_ARID) ,
        .M_AXI_ARADDR(M_AXI_ARADDR) ,
        .M_AXI_ARLEN(M_AXI_ARLEN) ,
        .M_AXI_ARSIZE(M_AXI_ARSIZE) ,
        .M_AXI_ARBURST(M_AXI_ARBURST) ,
        .M_AXI_ARLOCK(M_AXI_ARLOCK) ,
        .M_AXI_ARCACHE(M_AXI_ARCACHE) ,
        .M_AXI_ARPROT(M_AXI_ARPROT) ,
        .M_AXI_ARQOS(M_AXI_ARQOS) ,
        .M_AXI_ARVALID(M_AXI_ARVALID) ,
        .M_AXI_ARREADY(M_AXI_ARREADY) ,
        .M_AXI_RID(M_AXI_RID) ,
        .M_AXI_RDATA(M_AXI_RDATA) ,
        .M_AXI_RRESP(M_AXI_RRESP) ,
        .M_AXI_RLAST(M_AXI_RLAST) ,
        .M_AXI_RVALID(M_AXI_RVALID) ,
        .M_AXI_RREADY(M_AXI_RREADY)
    );


endmodule
